CREATE TABLE events
(
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                     VARCHAR(256)                            NOT NULL,
    location                 VARCHAR(255)                            NOT NULL,
    start_date_time          TIMESTAMP                               NOT NULL,
    end_date_time            TIMESTAMP                               NOT NULL,
    type                     VARCHAR(255)                            NOT NULL,
    status                   VARCHAR(255)                            NOT NULL,
    poster                   BYTEA,
    registration_start_date  DATE                                    NOT NULL,
    registration_end_date    DATE                                    NOT NULL,
    address                  VARCHAR(128)                            NOT NULL,
    description              VARCHAR(1024)                           NOT NULL,
    created_by_id            BIGINT,
    food_provided            BOOLEAN,
    created_at               TIMESTAMP                               NOT NULL,
    CONSTRAINT pk_events PRIMARY KEY (id)
);

ALTER TABLE events
    ADD CONSTRAINT fk_events_on_created_by FOREIGN KEY (created_by_id) REFERENCES users (id) ON DELETE SET NULL;
