CREATE TABLE attendance_records
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    event_id         BIGINT    NOT NULL,
    user_id          BIGINT    NOT NULL,
    checked_in_time  TIMESTAMP,
    CONSTRAINT pk_attendance_records PRIMARY KEY (id)
);

ALTER TABLE attendance_records
    ADD CONSTRAINT fk_attendance_records_on_event FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE CASCADE;

ALTER TABLE attendance_records
    ADD CONSTRAINT fk_attendance_records_on_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;

ALTER TABLE attendance_records
    ADD CONSTRAINT uq_attendance_records_event_user UNIQUE (event_id, user_id);
