CREATE TABLE registrations
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    event_id             BIGINT NOT NULL,
    user_id              BIGINT NOT NULL,
    registration_date    DATE   NOT NULL,
    gdpr_consent         BOOLEAN,
    photo_consent        BOOLEAN,
    food_preference      VARCHAR(16),
    transport_needed     BOOLEAN,
    driver_name          VARCHAR(64),
    driver_phone_number  VARCHAR(16),
    accommodation_needed BOOLEAN,
    accommodation_days   INTEGER,
    CONSTRAINT pk_registrations PRIMARY KEY (id)
);

ALTER TABLE registrations
    ADD CONSTRAINT fk_registrations_on_event FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE CASCADE;

ALTER TABLE registrations
    ADD CONSTRAINT fk_registrations_on_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;

ALTER TABLE registrations
    ADD CONSTRAINT uq_registrations_event_user UNIQUE (event_id, user_id);
