spring.application.name=CheckInApp
spring.config.import=optional:file:.env[.properties]

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.flyway.enabled=true
spring.flyway.clean-disabled=false
spring.flyway.validate-on-migrate=false

# JWT Configuration
jwt.secret=${JWT_SECRET:your-secret-key-must-be-at-least-32-characters-long-for-hs256-algorithm}
jwt.expiration=${JWT_EXPIRATION:3600000}

# Spring Cloud Discovery configuration
spring.cloud.discovery.enabled=false
cors.allowed-origins=http://localhost:4200